### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fableconf#1]
The event will be hosted under the umbrella F# foundation which help us with the promotion and other logistics. cc @mathias-brandewinder @ReedCopsey

It'd be great if we can have other sponsors to help us with the venue and lunch. Please add a comment with any ideas you may have.

**Comment by whitetigle** [comment]
So far we do have two confirmed local sponsors that will help us getting good prices for venues and food.

1. Le Syrpin (http://www.syrpin.org/).
2. Bordeaux Games (http://bordeauxgames.com/)

Maybe it would be great to have some financial support too?

**Comment by whitetigle** [comment]
As of today, after some talks, _Bordeaux Games will not be part of it ._ (lack of interest for F# for the gaming side)

**Le Syrpin**, through the person of Thierry Rouby, is still with us and has helped us so far for gathering a lot of precious information.
