### ISSUE TITLE
Video of talks

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fableconf#2]
It'll be very important to record the talks so other people can see them after the event. We'll try to ask the venue if they have such a service available but in last case we can use our own devices. I've got decent results using a camera and a wired mic to a phone, then matching the sound and image later with a video editor.

We may also consider the possibility of streaming the event.

**Comment by josselinauguste** [comment]
For your information, BdxIO is a tech conference held in Bordeaux for 3 years, and they own cameras and wireless headsets. I guess they may be ok to lend their equipment to other events (they already do so for the local java user group). How many conference tracks do you plan to have?

**Comment by whitetigle** [comment]
Hmm maybe 6 or 7? @alfonsogarciacaro?

**Comment by alfonsogarciacaro** [comment]
As we only have one room, I guess there'll be only one track (that is, only one talk at a time). As @whitetigle says, we'll probably have 6-7 talks plus a keynote and maybe 3 lightning talks.

**Comment by whitetigle** [comment]
Hi @josselinauguste is it still ok for the video equipement? 
What do I need to check in the conference room? (plugs, tables to put the cameras, etc..)?

**Comment by josselinauguste** [comment]
I should get the video equipment around the 18th or 19th. I still have to fond a tripod.  

In the room I'll only need a plug somewhere near the front row or the speaker, I'll use an extension cord and a multiple socket.  

Le 7 septembre 2017 à 17:23:23, Whitetigle (notifications@github.com(mailto:notifications@github.com)) a écrit:

**Comment by simax** [comment]
So were the talks recorded? Are they available anywhere?

**Comment by josselinauguste** [comment]
Yes they were, there is a little bit of post-production to be done, I hope they'll be released in the following weeks.
