### ISSUE TITLE
Caterer: LACOSTE TRAITEUR

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#20]
Adresse : 7 Avenue de la République  33320 EYSINES BORDEAUX  
Téléphone : 05 56 57 59 67  
Site : www.lacoste-traiteur.com

**Comment by whitetigle** [comment]
### Price 46€ / p

### Morning:

- Les Boissons Café, 
- assortiment de thés 
- Jus d'Orange, 
- eaux minérales plates 
- Mini croissant, 
- Mini pains aux raisins 
- Mini chocolatines

### All day:

- Café, 
- assortiment de thés 
- Jus d'ananas, 
- eau minérale plate

### Lunch:
**Cold:**

- Assortiment de Pintxos 
- Pintxos Chorizo  
- Pintxos Saumon
- Bodéga de MéliMélo de fèves et petits pois au 
- Pintxos Jambon de pays 
- jambon de canard 
- Ardoises de Charcuteries 
- Salade de nouilles chinoises, volaille laquée et légumes aux agrumes 
- Saucisse sèche, 
- grattons, 
- Jambon de pays 
- condiments et pain de campagne tranché 

**Cheese:**

- Fromages présentés en découpe cocktail 
- pain de campagne tranché

**Hot:** 

- Filet de Volaille, Poellée de champignons et haricots du jardin
- or Brandade de Saumon, purée de Pommes de terre  au citron vert

 
**Dessert:**

- Macarons de Saint Emilion 
- Cannelés Bordelais 
- Brochettes de fruits de saison

Café

**Comment by alfonsogarciacaro** [comment]
We should forget about the talks and just spent eating the whole day, I'm sure nobody will complain 😆

**Comment by whitetigle** [comment]
Or just talk while eating and drinking! 😆

**Comment by alfonsogarciacaro** [comment]
BTW, is there any caterer that you would recommend personally @whitetigle? Which ones seem to have the best quality/price ratio? ...Although we shouldn't take a worse menu only to save a few euros per person ;)

**Comment by whitetigle** [comment]
Well, I still need to get other quotations as well as more details from other caterers.
The one that appear here have already been "cleared".

Now we'll have the choice between 

1. "industrial grade", meaning they do that often with big companies, 
2. or small local ones which are renowned for their quality 

Anyway we're at about 40-50€/each all included (morning, lunch, afternoon + service).

So let's say we wait about 15 days and make a choice? I'll tell you then what seems best and why. Is that ok?

**Comment by whitetigle** [comment]
Ok so we have our winner: http://www.lagrifgourmande.fr/ (previously named Lacoste Traiteur).
I'm currently in conctact with Julie Rodriguez to setup the best menu for the best conference 😉
