### ISSUE TITLE
Caterer: L'oeil à la bouche

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#24]
AURÉLIEN CHEVY L'OEIL À LA BOUCHE
79 AVENUE LÉON BLUM
33110 LE BOUSCAT

06 64 69 64 80
a.chevy@orange.fr

http://www.loeilalabouche.fr/index.html

**Comment by whitetigle** [comment]
### Prix : 40 euros/personne  tout compris.

Cocktail Déjeunatoire:           

- Toast de tapenade à l'huile de truffe 
- Tartare de poissons au citron vert 
- croustillant d'escargot du bassin(2/pers) 
- Wrap de saumon fûmé et roquette(2/pers) 
- Navette au thon(2/pers) 
- Mousse de courgettes 
- Blinis et saumon marîné(2/pers) 
- Ardoise de cochonaille (Serrano, rosette, chorizo) 
- Brochette de gambas au tandoori(2/pers) 
- Toast de foie gras au Sauternes et gelée de raisin(2/pers) 
- Banc d'huîtres du Bassin(3/pers) pain de seigle, citron, beurre salé 
- Gaspacho au piment d'Espelette

Fromages, Ardoise : 
- Comté
- brie de Meaux
- Veille mimolette
- St-Maure et ses pains aux fruits.

Mignardises :

-   Tartelette citron meringué 
-   Sablé crème amande et fraise 
-   Ganache chocolat et framboise 
-   Panna cotta et mangue Café/thé

Pause café : 
- Corbeille de fruits 
- Café/thé 
- Jus d'orange 
- Mini-Viennoiseries ( Chocolatine, croissant,pain aux raisins) (matin)
- Canelé Bordelais (après midi)

Ce qui est inclus : 
- les Tables buffets,  
- les Manges debout, 
- le nappage, 
- les verres élégances, 
- la vaisselle de présentation et de service, 
- les serviettes en papiers 
- ainsi que le service qui sera assuré par des maîtres d'hôtel qualifiés .

Personnels (horaire de 7h30 à 18h):  
- 1 Maître d’hôtel, 
- 1 serveur voir 2 serveurs suivant le nombre d'invité, 
- 1 cuisinier ,  

Les produits sont issus d'un circuit court, producteurs locaux ou régionaux ,tels que maraîchers, Huîtres et poissons du Bassin, canard du Lot et Garonne......

**Comment by whitetigle** [comment]
English translation to come as well as other offers.

**Comment by alfonsogarciacaro** [comment]
Don't worry about English translation, food menus always sound much better in French ;)
