### ISSUE TITLE
CfP discussion

### ISSUE THREAD

**Issue by forki** [fable-compiler/fableconf#25]
@Krzysztof-Cieslak proposed to do CfP via github. Good? Other ideas?

**Comment by alfonsogarciacaro** [comment]
Yeah, having a CfP would definitely be a great idea. I have already contacted some potential speakers and my only fear is we end up with not many free spots available (we only have one track). I was thinking to follow F# eXchange model and have keynote, six 45 minute talks and 4 lightning talks. What do you think?

**Comment by forki** [comment]
yeah lightning talks are great

**Comment by josselinauguste** [comment]
yep lightning talks are great, and 6 talks + a keynote seems enough for an intense day :-)

A CFP is nice if you're not sure to find enough awesome talks, otherwise in regards to the limited number of talks, I'm not sure it is worth the effort. We may maybe only use the CFP for the lightning talks? And if we're doing so, I'm curious to see how it could be handled using Github issues :-)

**Comment by alfonsogarciacaro** [comment]
I guess by making people submit a proposal by opening an issue and there let others vote, although this could make it more awkward to reject a talk... or more embarrassing for us if there're not enough proposals ;)

**Comment by forki** [comment]
Chris said they did that for .NET fringe. But despite the name that conference is much more mainstream

**Comment by Krzysztof-Cieslak** [comment]
Actually the process wasn't issues + voting but submitting PR with your talk to the repo with all proposals. Selection process was still behind the scenes but at least you knew what talks were already submitted etc.

**Comment by alfonsogarciacaro** [comment]
Ok, at the moment we have three 45-min talks + keynote. So there are other three 45-min and four 15-min slots available, which should be enough for opening a CfP. If everybody agrees, I'll create an issue offering a template and ask people to send PRs with proposals. (The other option would be to use Google forms so the proposals are private.)

**Comment by Krzysztof-Cieslak** [comment]
Can be closed I guess

**Comment by alfonsogarciacaro** [comment]
We can still make room to a surprise speaker but if it happens it probably won't be through the CfP :wink: so we can close it, yes.
