### ISSUE TITLE
Staff & roles

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#26]
So far we have:

### Staff - On site

- linking, overall: @whitetigle
- video: @josselinauguste
- welcome desk: (check tickets, say hello, big hug, etc...): ?? (**english spoken** required)
- general inquiry, help desk: ?? (maybe same people, **english spoken** required)

### External
- Wine & Cheese & good wine & coffee-as-well management: **Caterer** 

### Other?
Any other roles?

**Comment by alfonsogarciacaro** [comment]
I volunteer for anything, including serving coffee and such if the staff is not provided by the caterer :)

**Comment by forki** [comment]
I assume we need a french speaking person to do all the communication with
caterers and other local people.

Am 04.05.2017 8:50 vorm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:

**Comment by whitetigle** [comment]
@alfonsogarciacaro Thanks! But I'm making sure that the caterer will do that.
@forki don't worry, I'll handle that.

**Comment by forki** [comment]
I did not worry. It's just the reason why I didn't volunteered for
administration desk.
That said I'm fine with everything where people don't get offended by my
french.

Am 04.05.2017 09:11 schrieb "Whitetigle" <notifications@github.com>:
