### ISSUE TITLE
Call for Presentations

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fableconf#29]
Hi Fablers!

As you (should) know, Fable community is [gathering for the first time in the amazing city of Bordeaux on Sept 22 for FableConf](https://www.eventbrite.es/e/fableconf-bordeaux-tickets-34089709238). We are very busy securing the important things: a venue, the food, :cheese: and 🍷 ... but someone also mentioned we should have some talks to honor the `conf` part in the name, and that's why we're opening (drums...) the **ACfAP**! :tada:

> ACfAP: Awesome Call for Awesome Presentations

At the moment we have 3 slots open for 45-min talks and 4 for 15-min length talks. Obviously we are looking for talks focused on Fable, but this can be also in combination with other F# or non-F# technologies. Also, we're very interested in practical talks ideally with impressive examples of Fable in action, not only targeting the web, but also mobile platforms (React Native, Fuse), desktop (Electron), Cloud or IoT. And we'd like to have not only apps, but also see how Fable can make games, interact with Sonic Pi for live music and any other crazy idea crossing your head right now ;)

We are using Github for the CfP (sorry, I mean ACfAP) so proposals are public and you can have a better idea of what's already covered. To submit a proposal, just send a PR to this repo with a markdown document to the `cfp` folder containing:

- Title
- Duration: 45 or 15 minutes
- Abstract
- Bio

[Example](https://github.com/fable-compiler/fableconf/blob/51802e7ef0efd2c1bb1a5165040f552d94c76a63/cfp/Elmish.md)

And now the caveat...

Speakers will get the ticket (including the food, cheese, wine, etc.) to the conference for free. However, we are still a small community and have a limited budget for the conference so unfortunately we don't know how much we can help speakers with travel costs until we see how many tickets are sold. For this reason, we cannot guarantee that we'll be able to cover flights or hotels as of now 😕 But if you bring many friends with you and we can sell out we will!

**Comment by whitetigle** [comment]
> And we'd like to have not only apps, but also see how Fable can make games, interact with Sonic Pi for live music and any other crazy idea crossing your head right now ;) 

Sure 👍 😜
