### ISSUE TITLE
Venues

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#3]
### ENSEIRB-MATMECA
_École Nationale Supérieure d'Électronique, Informatique, Télécommunications, Mathématique et Mécanique de Bordeaux._

website: https://enseirb-matmeca.bordeaux-inp.fr/en

Contacted through our local sponsors to get best prices
- Le Syrpin (http://www.syrpin.org/).
- Bordeaux Games (http://bordeauxgames.com/)

We may have also get some help for this venue through _Bordeaux functional meetup_ (https://www.meetup.com/bdx-fp/)

**Comment by whitetigle** [comment]
### Cap Sciences
_Museum of Sciences_
website: http://www.cap-sciences.net/qui-sommes-nous.html

Contacted directly.

**Comment by whitetigle** [comment]
### Bordeaux Chamber of Commerce and Industry
website: http://bordeauxgironde.cci.fr/

Not contacted yet but would any of the other venue fail, we could also ask them through our local sponsors.

**Comment by whitetigle** [comment]
Ok. Cap Sciences has been confirmed for September, the 22th for the whole day.

**Comment by forki** [comment]
Great!
