### ISSUE TITLE
FableConf is coming!

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fableconf#37]
![fableiscoming](https://user-images.githubusercontent.com/8275461/30154290-c1b80f86-93b9-11e7-936e-84d1f013cb22.jpg)

@et1975 @whitetigle @Krzysztof-Cieslak @MangelMaxime @xtuc @Indy9000 Hi everybody! I know you've been having that feeling for some days now, like a little tickling you may have not identified. Yes, it's FableConf approaching! 😄 I'm just opening this issue to make it easier for you to ask questions and also to make last announcements for speakers :+1:

Really looking forward to see you all there!

**Comment by Krzysztof-Cieslak** [comment]
Damn, that's subtle way of telling me that I need to prepare talk...

**Comment by whitetigle** [comment]
- So. Babbel, how do you find my English accent today? 
- Well.. As lovely as a French moo. Do you have any issue with your mic?

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak I believe it's a reminder for all of us :D

**Comment by alfonsogarciacaro** [comment]
Latest news:

- To make sure everybody will have a seat, the place for the workshops has changed. They will happen at [Bordeaux Digital Campus](https://www.google.fr/maps/place/Bordeaux+Digital+Campus/@44.863924,-0.5613694,16z/data=!4m5!3m4!1s0xd54d9a55ce015bf:0xd2da001c64f8dddc!8m2!3d44.863924!4d-0.556992), 5 minutes walking from Cap Sciences.
- The day before FableConf, Thursday 21st, the Bordeaux Software Craftsmanship Community will have a meetup. @Krzysztof-Cieslak [will talk there](https://www.meetup.com/software-craftsmanship-bdx/events/240001683/) and they're also looking for a second speaker. Will anyone be in Bordeaux that day and is interested in speaking? You can choose any subject you like :)

**Comment by Krzysztof-Cieslak** [comment]
My talk on the Meetup will be rather "light" (non technical). So something more F# related would be cool ;-)

**Comment by alfonsogarciacaro** [comment]
Moar news: we'll have a dinner on Friday evening after the talks (check the updated schedule at http://fable.io/fableconf for details) :wine: 🥘 This is open to attendees and speakers, but the budget should be enough to treat you on this one ;) If you want to come, please do a +1 reaction to this comment so we know how many people will be there to make the booking. Cheers!

**Comment by whitetigle** [comment]
Dear all!
Just so you know, at Cap-Sciences, we'll have 

- HD-Ready projector , meaning a great resolution of 1280x720!! 
- HDMI and VGA plugs 
- Mini Jack for audio
- 5 French power plugs as well.

I'll go there tomorrow afternoon at 15h30. Let me know if you need something special.

Have a nice day!

**Comment by whitetigle** [comment]
Regarding Workshops:

- WIFI 👍 
- seats
- tables
- great people 😁

**Comment by whitetigle** [comment]
**Regarding overall organization.**

On Friday, I'll be at Cap Sciences at 08:00. You can join me whenever you want.
We'll start at 08:30 with some ☕️, 🍵 🥐 

Would you have any question, you can contact me at the following number : +33 680 87 56 33 
I will try to answer all your questions with the most delicate English a South-western French man can produce 😬

**Comment by whitetigle** [comment]
Last but not least..

![keymaster](https://user-images.githubusercontent.com/883207/30634345-1869bbd8-9def-11e7-9102-3e8c8c0cd613.jpg)

**Comment by whitetigle** [comment]
Regarding overall organization.

On Friday, I'll be at Cap Sciences at 08:00. You can join me whenever you want.
We'll start at 08:30 with some ☕️, 🍵 🥐

And you got my phone number in your mail now ;)

**Comment by whitetigle** [comment]
Ah. By the way, **whatsapp** works too 👍
