### ISSUE TITLE
Website/Planning

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#42]
Everything about it!

**Comment by alfonsogarciacaro** [comment]
Pinging...

Speakers: @MangelMaxime @evelinag @selketjah @vbfox @theimowski @Zaid-Ajaj @StachuDotNet @Krzysztof-Cieslak @Dzoukr @rommsen
Organizers: @whitetigle @isaacabraham @forki 

@forki Can you please add mentions/get in touch with the remaining speakers from Remmidemmi track (Sia, Jeff Hollan, Ketleen)?

Thanks to @whitetigle we finally have a nice-looking site and we're starting to concrete the planning. We've published a draft [here](http://fable.io/fableconf/#planning-super-secret) (note the link is hidden from the navbar, you can also manually add the `planning-super-secret` hash). Some of you have already sent me info about your bio, the picture you want to use and the title and abstract of the talk, so I'll try to fill the holes during this week. But if you have a moment and you can use the online-edit to add your information [in this file](https://github.com/fable-compiler/fableconf/blob/neon/src/Planning/Speakers.fs) it would be really helpful :smile:

Thanks a lot in advance, and looking forward to seeing you all in the conference!

**Comment by forki** [comment]
hey, I really LOVE the new design! Kudos.
But can someone please increase font size of the white text?

**Comment by forki** [comment]
@alfonsogarciacaro I wrote to sia - he wants to talk to jeff and send me everything

**Comment by whitetigle** [comment]
@forki sorry I just came back. So do you want to increase the font size in general? Are you reading on desktop or mobile? Just so I know If I need to change all devices profiles.

**Comment by alfonsogarciacaro** [comment]
BTW, I already increased the font size (to 1.2rem) when the screen is wider than 400px.
