### ISSUE TITLE
Venues

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#43]
Everything about them!

**Comment by josselinauguste** [comment]
In which city will it be held?

**Comment by whitetigle** [comment]
Maybe Berlin? Maybe Oslo? Maybe Valencia? Maybe Bordeaux? Maybe @alfonsogarciacaro will host the event in his castle in the center of Madrid?

We don't know yet. But it will be held in Europe 😉

**Comment by josselinauguste** [comment]
Ho ok, I thought you were on 🔥 again 😄

**Comment by whitetigle** [comment]
😆 Oh well not today. But who knows? If all else fails... 😉 
Meanwhile we do have to do some meetup in Bordeaux I Think to have a few drinks with our fellow Frencharpists 🍻 (but that's another discussion)

**Comment by xtuc** [comment]
I'm proposing to host it in Strasbourg! We have great venues at the Strasbourg university. I can help with the organization.

I think that it's the ideal location because is central and close to UK or Germany.

**Comment by whitetigle** [comment]
@xtuc , are you on the F# slack? If so what's your handle?

**Comment by xtuc** [comment]
@whitetigle I didn't join it, could we invite me (email on my profile) or sent me the link to the registration please?

**Comment by whitetigle** [comment]
Here it is: http://fsharp.org/guides/slack/

**Comment by whitetigle** [comment]
I've also asked on slack (maybe it's faster? @alfonsogarciacaro?)

**Comment by xtuc** [comment]
I'm in, it's sven

**Comment by alfonsogarciacaro** [comment]
Finally the event will be held in [Microsoft Berlin](https://www.microsoft-berlin.de/).
