### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#45]
Everything about all the money we're going to get from our awesome sponsors!

**Comment by whitetigle** [comment]
... And other kind of sponsorships as well 😄

**Comment by alfonsogarciacaro** [comment]
Currently we have Microsoft (venue), fsharp.org and compositional-it. After finishing the planning we can try to catch more sponsors and decider which kind of sponsorship we can offer.

**Comment by Krzysztof-Cieslak** [comment]
We may be interested in sponsoring, please let me know when you will know anything. :-)

**Comment by alfonsogarciacaro** [comment]
That's great @Krzysztof-Cieslak, thank you! Now...

![image](https://user-images.githubusercontent.com/8275461/44519688-0a3c5500-a6ce-11e8-907a-20a8c3c68f61.png) ;)
