### ISSUE TITLE
Talk recording

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#48]
Speakers (Friday): @MangelMaxime @evelinag @selketjah @vbfox @theimowski @Zaid-Ajaj @Krzysztof-Cieslak @jfellien @Dzoukr @rommsen @dersia

Organizers: @whitetigle @isaacabraham @forki @alfonsogarciacaro 

AV Expert: @fergusmeiklejohn

We're planning to record the talks on Friday and it'll be great if we could record also the computer screens, so it'll be very helpful if you could make sure you're able to record your screen. You can use any app you like but on macOS [quicktime should be enough](https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac) and with Windows 10 apparently you can use Windows+G to open the Game Bar which also offers screen recording.

If you've read this comment and you know how to record your screen, it'll be very helpful if you could add a :+1: to this comment. If you've questions, please add them below.

**Comment by Dzoukr** [comment]
For people on Windows, you can download Microsoft Expression Encoder 4 having quite powerful screen recoder for free : https://www.microsoft.com/en-us/download/details.aspx?id=18974

**Comment by rommsen** [comment]
I am using [OBS ](https://obsproject.com/) on Windows (also available on Mac and Linux). Works great for me and is also free.

**Comment by vbfox** [comment]
Never recorded for anything else than gaming, I'll try to setup something :)

**Comment by MangelMaxime** [comment]
For info, OBS seems to be working on Linux if we don't scale down the recording resolution. Otherwise, everything looks ugly.

**Comment by alfonsogarciacaro** [comment]
Hi everybody! First of all, thank you very much for the great talks! Fergus is already preparing the videos and they look great. But I forgot to ask some of you to put the screen recordings in the USB, sorry! If you have the recordings in your computer, can you upload them somewhere and provide a link?

These are the ones we're missing: @Dzoukr @rommsen @dersia

Thanks again!

**Comment by rommsen** [comment]
Unfortunately the screen recording was not working for me (black screen). I talked to @fergusmeiklejohn about it and he agreed to send me a link to the video material he recorded of my talk. I will then rerecord my screen according to the material and upload it somewhere.

@fergusmeiklejohn do you think you could give me the material any time soon? I have some spare time on Thursday and Friday where I could do this.
