### ISSUE TITLE
Transportation

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#5]
## Direct Shuttle from the airport to the train station: 

- **time**: 30'
- **price**: 8€ (one way)

>  timetables: http://30direct.com/en/high-season-schedule/
>  fares: http://30direct.com/en/tarifs-vente-tickets/ 

## Tram from the train station to Cap-Sciences

- **time**: 22'
- **price**: 1.50€ (one way)

1 - Tram C from Train station (Gare St Jean) to Quinconces (direction> Gare de Blanquefort)  (15 minutes)
2 - Change tram lines
3 - Tram B from Quinconces to Cité du vin (7 minutes)

> more information here: https://www.infotbm.com/en

**Comment by whitetigle** [comment]
[Map](https://www.google.com/maps/dir/Gare+Saint-Jean,+Bordeaux,+France/Cap+Sciences,+Hangar+20,+Quai+de+Bacalan,+33300+Bordeaux,+France/@44.8431262,-0.5816984,14z/am=t/data=!4m14!4m13!1m5!1m1!1s0xd5526492c8365af:0x24c6bd58a0525021!2m2!1d-0.556682!2d44.8258841!1m5!1m1!1s0xd55288fe041f36f:0xc849cfd5c16a7bb8!2m2!1d-0.5541406!2d44.8597508!3e3?hl=en-US)

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks!
