### ISSUE TITLE
June - meetup

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fableconf#6]
In order to prepare Bordeaux for the arrival of FableConf and present F# to the crowds, @josselinauguste  proposed that we make a pre-FableConf. 

So after some discussion, here are the first details:
- it should happen in Bordeaux in June (end of month)
- it will be hosted by [Bordeaux Functional Meetup](https://www.meetup.com/bdx-fp/) whose organizer, @nsteenv, has kindly offered his help regarding the organization.
- the date will be confirmed by the end of May

**Comment by alfonsogarciacaro** [comment]
That's a very nice idea! It may be a bit difficult for me to attend in person but maybe I could be there by videoconf?

**Comment by whitetigle** [comment]
Ok we'll try to setup a videoconf. I'll ask @nsteenv

**Comment by whitetigle** [comment]
ping @josselinauguste (cf #2)

**Comment by josselinauguste** [comment]
When we'll have the meetup date, I'll try to get some video equipment from the BdxIO team

**Comment by nsteenv** [comment]
No problem for videoconf (if you have the equipment), just let me know when you have the date and I'll book the place.

**Comment by whitetigle** [comment]
Ok @josselinauguste just created the event. 🥂   
More info [there](https://www.meetup.com/software-craftsmanship-bdx/events/240204501/?a=socialmedia)
