### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fableconf#7]
We need a website and EventBrite asap to start selling tickets and get a better estimation of how many people would be interested to come. Probably a single page would be enough, maybe using [SinglePaged](https://github.com/t413/SinglePaged). Ideas?

Using the `gh-pages` in this repo means we can use the `fable.io/fableconf` URL which is nice :)

cc @MangelMaxime

**Comment by forki** [comment]
regarding tickets - is there a legal entity that does that?

**Comment by alfonsogarciacaro** [comment]
Finally I could finish a first version of the website, you can check it [here](http://fable.io/fableconf). It's still too simple but hopefully people with better design skills than can work from there :smile: Obviously the web is made with the Fable.Elmish template and it's also using the Fable.Elmish.Bulma library by @MangelMaxime. You can find the source code in the `gh-pages` branch of this repo.

Before announcing it, @et1975, @whitetigle, @MangelMaxime, @Indy9000, @xtuc, @Krzysztof-Cieslak, could you please check that everything is fine in your speaker card? You can click on the talk title to see the abstract. Please tell me if you want to use another picture. And it'd be also nice to have the missing title/abstract/bios in the upcoming days (mine included :wink:).

**Comment by forki** [comment]
what's bulma?

**Comment by et1975** [comment]
Looks sweet and simple, very nice!

**Comment by MangelMaxime** [comment]
@forki Bulma is a [CSS framework based on Flexbox](http://bulma.io/)

[https://mangelmaxime.github.io/Fable.Elmish.Bulma/#elements/button) providing is a library providing helpers to use the lib in a fully typed way.

@alfonsogarciacaro Looks nice :)

**Comment by whitetigle** [comment]
That's just awesome @alfonsogarciacaro! Bravo! 🙌 🍾 
Seems 👍 for me.

**Comment by alfonsogarciacaro** [comment]
@whitetigle Hehe, I was hoping you would send an actual picture :wink: Also, we need to add the food menu to the web, this will appeal many more people for sure 🍗

**Comment by xtuc** [comment]
Yes, the website looks good and my picture is good. Thanks.

We could have more space for the abstracts, what do you think about something like that? 
![screenshot from 2017-07-06 21-52-01](https://user-images.githubusercontent.com/1493671/27930006-67409db6-6295-11e7-824f-db6c5e0c6d60.png)

**Comment by whitetigle** [comment]
@alfonsogarciacaro sure I'll send a pic and add the menu :)

**Comment by Indy9000** [comment]
Looks great!

**Comment by MangelMaxime** [comment]
@xtuc I prefer the compact version of Alfonso :) because it's more balanced.

Also, we will move the menu from the left to the top, so we will gain space for the tiles here too. So we should have a good compromise between both solutions.

**Comment by alfonsogarciacaro** [comment]
Thanks for the confirmation @xtuc. Adding the abstracts to the main page directly is an interesting idea though some of them are a bit long (check François' one :wink:) and I'm not sure how well they'd fit in mobile, but we can consider it :+1:
