### ISSUE TITLE
Q: copy and paste song?

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fableconf#70]
What was the music used for the copy-paste song?

**Comment by alfonsogarciacaro** [comment]
The name is "Shiawase" (Happiness) and it's from Japanese TV program for children. The original cannot be seen online but there're [several versions in youtube](https://www.youtube.com/results?search_query=%E3%82%B7%E3%82%A2%E3%83%AF%E3%82%BB%E3%80%80%E3%81%8A%E6%AF%8D%E3%81%95%E3%82%93%E3%81%A8%E3%81%84%E3%81%A3%E3%81%97%E3%82%87) (we used the instrumental one).

**Comment by nojaf** [comment]
Thanks!
