### ISSUE TITLE
Don't show mas.jpg on mobile

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fableconf#72]
Hi, I've just received a remark that the site is slow on mobile.
I think it is because of https://fable.io/fableconf/mas.jpg being downloaded (1.7 MB)
Could we use another image on mobile?

**Comment by whitetigle** [comment]
Sure ! Will prepare that 👍

**Comment by whitetigle** [comment]
Should be ok now. Can you confirm on your side?

**Comment by nojaf** [comment]
Yes, perfect.
